### PR TITLE
Adding KF 1.4 release with new istio 1.11 and cert-manager 1.15 to Openshift

### PR DESCRIPTION
**Pull request by nakfour**
**Which issue is resolved by this Pull Request:**
Resolves #https://issues.redhat.com/browse/ODH-445
Please test this PR on OCP 4.8 or lower, support for the full KF stack on Kubernetes 1.22 is not available yet.
**Description of your changes:**

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

### CODE REVIEW

**Comment by jkoehler-redhat** [comment]
@nakfour do you have the differences in what was brought in and what was changed on our end to work with OpenShift?

**Review by crobby — DISMISSED** [review]
Tried with a kfdef consisting of openshift-scc, istio, cert-manager, and kubeflow-apps (which is evidently required).
Looks like kubeflow-apps needs an update from v1beta1.  I will investigate more and advise.

`WARN[0099] Encountered error applying application kubeflow-apps:  (kubeflow.error): Code 500 with message: Apply.Run : [unable to recognize "/tmp/kout657981556": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1", unable to recognize "/tmp/kout657981556": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]  filename="kustomize/kustomize.go:284"`

**Comment by nakfour** [comment]
@crobby KF does not work on OCP 4.9 today, the KF community is marching towards Kubernetes 1.22

**Comment by nakfour** [comment]
@jkoehler-redhat all the changes are in this PR

**Comment by nakfour** [comment]
@crobby we can merge this by testing it on OCP 4.8 and later. This is slated for ODH 1.1.2

**Comment by nakfour** [comment]
@jkoehler-redhat yes these 79 files are all customizations to work on OCP. This is the whole KF stack we are fixing not just one component

**Comment by nakfour** [comment]
@LaVLaS found a bug with the logout button on the dashboard, opened an issue for it: https://issues.redhat.com/browse/ODH-577

**Comment by LaVLaS** [comment]
I encountered this error when trying to create an experiment
```
{"error":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","code":3,"message":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references.","details":[{"@type":"type.googleapis.com/api.Error","error_message":"In single-user mode, CreateExperimentRequest shouldn't contain resource references.","error_details":"Validate experiment request failed.: Invalid input error: In single-user mode, CreateExperimentRequest shouldn't contain resource references."}]}
```

**Comment by LaVLaS** [comment]
The example `[Demo] flip-coin` pipeline is created and runs successfully but it is never shown in the UI

**Comment by LaVLaS** [comment]
I deployed this into a fresh cluster using `kfctl` and it was successful but I did have the same issues with creating experiments and missing pipeline runs.  Since this is a RC build do you want to keep working on this PR to resolve this issue or merge it with follow-up PRs to fix the errors?

**Comment by LaVLaS** [comment]
After an offline conversation with @nakfour, the issues were related to selecting a user namespace prior to creating the experiment and pipelines.  Leaving the namespace selector at the default `Select namespace` "resolved" the issue of the missing experiment and pipeline

**Review by LaVLaS — APPROVED** [review]
/lgtm

This worked for me on OCP 4.8

**Review by crobby — APPROVED** [review]

**Pull request merged**
