### PR TITLE
Update Pytorch Operator and remove OpenShift overlay

### LINKED ISSUE #55: Update Pytorch operator image
Latest version of Pytorch image should have the fixes introduced by OpenShift overlay

### PR DESCRIPTION
**Pull request by vpavlin**
**Which issue is resolved by this Pull Request:**
Resolves #55 

**Description of your changes:**

Latest version of the image has the OpenShift fixes which we temporarily added via OPenShift overlay

**Checklist:**

* The updated KFdef: https://github.com/opendatahub-io/odh-manifests/blob/e5720d80129b735906ac62e262ec651eb2185c35/kfdef/kfctl_openshift_mix.yaml
* You need to change manifests URL to: https://api.github.com/repos/opendatahub-io/manifests/tarball/pull/56/head

### CODE REVIEW

**Comment by vpavlin** [comment]
Also part of https://github.com/opendatahub-io/odh-manifests/issues/147

**Comment by nakfour** [comment]
This worked for me, tried both tfjob and pytorchjob mnist examples.
/lgtm

**Pull request merged**
