### PR TITLE
Update Katib images and patch SCC injection

### PR DESCRIPTION
**Pull request by vpavlin**
**Which issue is resolved by this Pull Request:**
This PR allows us to go back to using upstream images for Katib (instead of our own custom ones)

**Description of your changes:**
Updating all Katib images to 0.8.0 which has OpenShift needed changes

**Checklist:**

Clone the PR
```
sed': sed -i 's#uri: .*#uri: '$PWD'#' ./kfdef/kfctl_openshift.yaml
kfctl build -V -f kfdef/kfctl_openshift.yaml
kfctl apply -f kfdef/kfctl_openshift.yaml 
```

Katib should deploy without issues

### CODE REVIEW

**Comment by crobby** [comment]
So, was this also included upstream on the 0.7.0 branch?  If not, it's sort of against our pattern of only modifying the overlays.  
Just making sure that the deviance from our style was intentional.
I will test this out later today.

**Comment by vpavlin** [comment]
No, it was only updated in master: https://github.com/kubeflow/manifests/commit/e9b5acd6a2f9b45a6f9861fbd4abbe1bebe7f260#diff-32b296860cd81cb851224586a69dca37

and I cherry-picked from there. Now the question is, what is better - cherry-pick a change from master, or maintain custom images.

What do you think?

**Comment by crobby** [comment]
> No, it was only updated in master: [kubeflow@e9b5acd#diff-32b296860cd81cb851224586a69dca37](https://github.com/kubeflow/manifests/commit/e9b5acd6a2f9b45a6f9861fbd4abbe1bebe7f260#diff-32b296860cd81cb851224586a69dca37)
> 
> and I cherry-picked from there. Now the question is, what is better - cherry-pick a change from master, or maintain custom images.
> 
> What do you think?

I'm ok either way.  Just don't want us to inexplicably drift from upstream.  Since it's also upstream, I'm not choosy on how we get it into our repo.

**Comment by vpavlin** [comment]
I did one more test and noticed they changed the name of `katib-manager` to `katib-db-manager` looking at cherry-picking that one as well..

**Comment by vpavlin** [comment]
@crobby Sorry for asking for another review:) The PR is completely different - had to pull in 3 more commits since there were couple other changes below which broke with just one cherry-picked commit.

For the changes **I** made, please see the top commit - I added that injection option and swapped database to rhscl/mysql8 - which also needed modified secret (more config options for mysql)

**Comment by crobby** [comment]
> @crobby Sorry for asking for another review:) The PR is completely different - had to pull in 3 more commits since there were couple other changes below which broke with just one cherry-picked commit.
> 
> For the changes **I** made, please see the top commit - I added that injection option and swapped database to rhscl/mysql8 - which also needed modified secret (more config options for mysql)

No problem.  I'll take a look at this today (tomorrow at the latest).

**Pull request merged**
