### PR TITLE
Adding VS to enable metadata

### PR DESCRIPTION
**Pull request by nakfour**
Which issue is resolved by this Pull Request:
Resolves #https://issues.redhat.com/browse/ODH-475

To test:
1. install Kubeflow using the manifest from this PR
2. In kubeflow namespace check for metadata virtual service that it exists
3. Launch the dashboard, run the example pipeline and check that there is metadata in the artifact tab

### CODE REVIEW

**Comment by crobby** [comment]
Quick question...what is "VS" as mentioned in the title here?

**Comment by crobby** [comment]
> Quick question...what is "VS" as mentioned in the title here?

Nevermind, I astutely sorted out that VS == VirtualService after actually looking at the code.

**Comment by VaishnaviHire** [comment]
Tested this successfully.
Virtual Service:
```
 oc get vs/metadata-grpc -n kubeflow     
NAME            GATEWAYS               HOSTS   AGE
metadata-grpc   ["kubeflow-gateway"]   ["*"]   106m
```

Artifacts:
Screen Shot 2021-09-21 at 1 34 39 PM

**Pull request merged**
