### PR TITLE
Add Kubeflow example for ODH operator

### PR DESCRIPTION
**Pull request by vpavlin**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

Add an KFDef example tested with ODH operator which can be linked from operator description in OLM

### CODE REVIEW

**Comment by crobby** [comment]
Should all the commented out bits be left there or cleaned up? Entire components just commented out without more context might not be that useful.

**Comment by LaVLaS** [comment]
In a follow up PR we should add a comment to describe when you should uncomment each comment block.

As @crobby stated in group chat, I won't vote to block based on this reqeusted change

**Comment by LaVLaS** [comment]
Can we change the name to something specific to why this is different than `kfctl_openshift.yaml`?  Both should be updated to `apiv1` since the operator watches `kfdef.apps.kubeflow.org/v1`

**Comment by nakfour** [comment]
@LaVLaS is you install manually using `kfctl` tool you don't need `kfdef.apps.kubeflow.org/v1`

**Comment by LaVLaS** [comment]
I don't have any objections with the name. Originally I was confusing this with the a PR in `odh-manifests` where we do need to update the `apiVersion` so that it works with the operator

**Pull request merged**
